# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('track', s3direct.fields.S3DirectField()),
                ('image', s3direct.fields.S3DirectField()),
                ('length', models.DurationField(blank=True, editable=False, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.Artist')),
            ],
        ),
    ]
