# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20160702_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, choices=[('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Jazz', 'Jazz'), ('Punk', 'Punk'), ('Reggae', 'Reggae'), ('Rock', 'Rock')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=s3direct.fields.S3DirectField(default='Rock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track',
            field=s3direct.fields.S3DirectField(default='Rock'),
            preserve_default=False,
        ),
    ]
