# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20160702_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.CharField(max_length=256, default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='track',
            field=models.CharField(max_length=256, default=''),
        ),
    ]
