# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_auto_20160702_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='length',
        ),
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
