# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_auto_20170211_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.CharField(max_length=256),
        ),
    ]
